# Generated by Django 4.2.7 on 2023-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=80)),
                ("url", models.CharField(max_length=500)),
            ],
        ),
    ]
