# Generated by Django 4.2.7 on 2023-11-22 16:53

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchrequest",
            name="url",
            field=models.CharField(
                max_length=500, validators=[backend.models.validate_olx_url]
            ),
        ),
    ]
