# Generated by Django 4.2.7 on 2023-11-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_searchrequest_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchRequestResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "search_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.searchrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchRequestResultEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.FloatField()),
                (
                    "search_request_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.searchrequestresult",
                    ),
                ),
            ],
        ),
    ]
