# Generated by Django 4.2.7 on 2023-12-08 23:17

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_searchrequestresult_searchrequestresultentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchrequest",
            name="url",
            field=models.CharField(
                max_length=1000, validators=[backend.validators.validate_olx_url]
            ),
        ),
    ]
